services:
  - type: web
    name: nutrition-training-planner
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    healthCheckPath: "/"
    healthCheckTimeout: 100
    autoDeploy: true
